CineSearch\TdcpBundle\Entity\Film:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        image:
            type: blob
        genre:
            type: string
            length: 255
        acteurs:
            type: string
            length: 255
        cinema:
            type: string
            length: 255
        date:
            type: string
            length: 255
        synopsis:
            type: text
        trailer:
            type: string
            length: 255
    lifecycleCallbacks: {  }
